apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-vc1
provisioner: csi.trident.netapp.io
parameters:
  backendType: "ontap-nas"
  storagePools: "vc1:aggr1"
allowVolumeExpansion: true
