kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sc3-1
  annotations:
    volume.beta.kubernetes.io/storage-class: storage-class-nas
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
