apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: backend-tbc-ontap-nas-east
spec:
  version: 1
  backendName: nas-east
  storageDriverName: ontap-nas
  managementLIF: 192.168.0.135
  storagePrefix: east_
  credentials:
    name: ontap-nfs-svm-secret-username
  supportedTopologies:
    - topology.kubernetes.io/region: trident
    - topology.kubernetes.io/zone: east