kind: Pod
apiVersion: v1
metadata:
  name: centos-east
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.kubernetes.io/zone
            operator: In
            values:
             - east1
  volumes:
    - name: nfsstorage
      persistentVolumeClaim:
       claimName: pvc-east
  containers:
    - name: centos
      image: centos:centos7
      command:
        - /bin/sh
        - "-c"
        - "sleep 60m"
      volumeMounts:
        - mountPath: "/data"
          name: nfsstorage
