apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-topology
provisioner: csi.trident.netapp.io
volumeBindingMode: WaitForFirstConsumer
allowedTopologies:
- matchLabelExpressions:
  - key: topology.kubernetes.io/zone
    values:
    - east
    - west
  - key: topology.kubernetes.io/region
    values:
    - trident
parameters:
  backendType: "ontap-nas"
  storagePools: "nas-east:aggr1;nas-west:aggr1"