apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storage-class-nas
provisioner: csi.trident.netapp.io
parameters:
  backendType: "ontap-nas"
  storagePools: "NAS_with_snapdir_on:aggr1"
