---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-proxy
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: sc-proxy
---
kind: Pod
apiVersion: v1
metadata:
  name: busybox-proxy
spec:
  volumes:
    - name: volume
      persistentVolumeClaim:
       claimName: pvc-proxy
  containers:
    - name: debugger
      image: registry.demo.netapp.com/busybox:1.35.0
      imagePullPolicy: IfNotPresent
      command: ['sleep', '3600']
      volumeMounts:
        - mountPath: "/data"
          name: volume