apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: backend-tbc-ontap-san-secured
spec:
  version: 1
  backendName: svm-secured-iscsi
  storageDriverName: ontap-san
  managementLIF: 192.168.0.210
  storagePrefix: sec_
  useCHAP: 'true'
  credentials:
    name: ontap-iscsi-secured-secret