alertmanager:
  enabled: false
  
nodeExporter:
  enabled: false

prometheus:  
  service:
    nodePort: 32105
    type: NodePort
  
grafana:
  image:
    repository: registry.demo.netapp.com/grafana/grafana
    tag: 9.1.4
  persistence:
    enabled: true
    accessModes:
      - ReadWriteMany
  service:
    nodePort: 30267
    type: NodePort