apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache
spec:
  selector:
    matchLabels:
      app: apache
  replicas: 2
  template:
    metadata:
      labels:
        app: apache
    spec:
      volumes:
      - name: apache-data
        persistentVolumeClaim:
          claimName: pvc-apache
      containers:
      - name: apache
        image: php:7.0-apache
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: "/var/www/html/"
          name: apache-data
