apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-grafana-datasources
  namespace: monitoring
  labels:
     grafana_datasource: "1"
data:
  prometheus.yaml: |-
    {
        "apiVersion": 1,
        "datasources": [
            {
                "name": "prometheus",
                "type": "prometheus",
                "url": "http://192.168.0.140",
                "isDefault": "true"
            }
        ]
    }