apiVersion: apps/v1
kind: Deployment
metadata:
  name: blogclone
  labels:
    scenario: clone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blogclone
  template:
    metadata:
      labels:
        app: blogclone
    spec:
      containers:
      - name: blog
        image: ghost:3.13-alpine
        ports:
        - containerPort: 2368
        env:
        - name: url
          value: http://192.168.0.63:30081/
        volumeMounts:
        - mountPath: /data
          name: content
      volumes:
      - name: content
        persistentVolumeClaim:
          claimName: mydata-from-snap
