apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: backend-tbc-ontap-nas-eco-limit-volsize
spec:
  version: 1
  backendName: nas-eco-limit-volsize
  storageDriverName: ontap-nas-economy
  managementLIF: 192.168.0.135
  limitVolumeSize: 10g
  storagePrefix: sc08_4_
  credentials:
    name: ontap-nfs-svm-secret-username