---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-proxy
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: sc-proxy
---
kind: Pod
apiVersion: v1
metadata:
  name: centos-proxy
spec:
  volumes:
    - name: nfsstorage
      persistentVolumeClaim:
       claimName: pvc-proxy
  containers:
    - name: centos
      image: centos:centos7
      command:
        - /bin/sh
        - "-c"
        - "sleep 60m"
      volumeMounts:
        - mountPath: "/data"
          name: nfsstorage
