---
- hosts: localhost
  collections:
    - netapp.ontap

  vars:
    recurrent_parameters: &recurrent_parameters
      hostname: 192.168.0.101
      username: admin 
      password: Netapp1!
      https: true
      validate_certs: false

  tasks:
  - name: Disable Showmount
    netapp.ontap.na_ontap_nfs:
     state: present
     showmount : disabled
     vserver: svm_secured
     <<: *recurrent_parameters