apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storage-class-nas-domain
provisioner: csi.trident.netapp.io
parameters:
  backendType: "ontap-nas"
  storagePools: "nas-domain:aggr1"
allowVolumeExpansion: true