kind: Pod
apiVersion: v1
metadata:
  name: busybox-pod1
spec:
  volumes:
    - name: volume
      persistentVolumeClaim:
       claimName: pvc1
  containers:
    - name: debugger
      image: busybox
      imagePullPolicy: IfNotPresent
      command: ['sleep', '3600']
      volumeMounts:
        - mountPath: "/data"
          name: volume