kind: Pod
apiVersion: v1
metadata:
  name: busybox-pod4
spec:
  volumes:
    - name: volume
      persistentVolumeClaim:
       claimName: pvc4
  containers:
    - name: debugger
      image: busybox
      command: ['sleep', '3600']
      volumeMounts:
        - mountPath: "/data"
          name: volume