kind: Pod
apiVersion: v1
metadata:
  name: busybox-pod3
spec:
  volumes:
    - name: volume
      persistentVolumeClaim:
       claimName: pvc3
  containers:
    - name: debugger
      image: busybox
      command: ['sleep', '3600']
      volumeMounts:
        - mountPath: "/data"
          name: volume