apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-svm-secured-nas
provisioner: csi.trident.netapp.io
allowVolumeExpansion: true
parameters:
  backendType: "ontap-san"
  storagePools: "SVM_Secured_NFS:aggr1"