apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: backend-tbc-ontap-nas-qos
spec:
  version: 1
  backendName: nas-qos
  storageDriverName: ontap-nas
  managementLIF: 192.168.0.135
  storagePrefix: qos_
  credentials:
    name: ontap-nfs-svm-secret-username
  storage:
  - labels:
      performance: qos500iops
    defaults:
      qosPolicy: QoS_500iops
  - labels:
      performance: qos100MBps
    defaults:
      qosPolicy: QoS_100MBps
  - labels:
      performance: aQoS
    defaults:
      adaptiveQosPolicy: aQoS