apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-qos3
provisioner: csi.trident.netapp.io
allowVolumeExpansion: true
parameters:
  backendType: "ontap-nas"
  media: "ssd"
  selector: "performance=aQoS"