apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-qos1
provisioner: csi.trident.netapp.io
allowVolumeExpansion: true
parameters:
  backendType: "ontap-nas"
  selector: "performance=qos500iops"