kind: Pod
apiVersion: v1
metadata:
  name: podsnap
spec:
  volumes:
    - name: flexvol
      persistentVolumeClaim:
       claimName: pvc-nas
    - name: qtree1
      persistentVolumeClaim:
       claimName: pvc-nas-qtree
    - name: qtree2
      persistentVolumeClaim:
       claimName: pvc-nas-qtree2
  containers:
    - name: task-pv-container
      image: alpine:3.2
      command:
        - /bin/sh
        - "-c"
        - "sleep 60m"
      volumeMounts:
        - mountPath: "/data_vol"
          name: flexvol
        - mountPath: "/data_qtree1"
          name: qtree1
        - mountPath: "/data_qtree2"
          name: qtree2
