kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-nas-qtree2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: storage-class-nas-qtree
