apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storage-class-nas-qtree
provisioner: netapp.io/trident
parameters:
  backendType: "ontap-nas-economy"
  storagePools: "ECO_with_snapdir_on:aggr1"
