apiVersion: trident.netapp.io/v1
kind: TridentOrchestrator
metadata:
  name: trident
spec:
  debug: false
  namespace: trident
  tridentImage: registry.demo.netapp.com/trident:23.07.0
  autosupportImage: registry.demo.netapp.com/trident-autosupport:23.07.0