kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-nas-flexgroup
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: storage-class-nas-flexgroup