kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-storagepool
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: storage-class-storagepool
