kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-san-snap
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: storage-class-san-snap
