kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-nas-split
  annotations:
    trident.netapp.io/splitOnClone: pvc-nas
    trident.netapp.io/splitFromClone: "true"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: storage-class-nas
