kind: Pod
apiVersion: v1
metadata:
  name: centos
spec:
  volumes:
    - name: NFSstorage
      persistentVolumeClaim:
       claimName: pvc-to-resize
  containers:
    - name: centos
      image: centos
      command:
        - /bin/sh
        - "-c"
        - "sleep 60m"
      volumeMounts:
        - mountPath: "/data"
          name: NFSstorage
