apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storage-class-san-economy
provisioner: csi.trident.netapp.io
parameters:
  backendType: "ontap-san-economy"
  storagePools: "SAN_ECO-default:aggr1"
  fsType: "ext4"