apiVersion: capsule.clastix.io/v1beta1
kind: Tenant
metadata:
  name: tenant2
spec:
  owners:
  - name: owner2
    kind: User
  namespaceOptions:
    quota: 1
  nodeSelector:
    tenant2: "true"
  storageClasses:
    allowed:
    - sc-tenant2