apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: backend-tbc-ontap-nas-vsp
spec:
  version: 1
  backendName: nas-vsp
  storageDriverName: ontap-nas
  managementLIF: 192.168.0.135
  nfsMountOptions: nfsvers=3
  storagePrefix: vsp_
  defaults:
    spaceReserve: none
    encryption: 'false'
    unixPermissions: '0755'
    exportPolicy: default
    snapshotDir: 'false'
  credentials:
    name: ontap-nfs-svm-secret-username
  storage:
  - labels:
      app: myapp1
      cost: '100'
    defaults:
      spaceReserve: volume
      snapshotDir: 'true'
      unixPermissions: '0744'
  - labels:
      app: myapp2
      cost: '75'
    defaults:
      spaceReserve: volume
      snapshotDir: 'true'
      unixPermissions: '0777'
  - labels:
      app: myapp3
      cost: '50'
    defaults:
      spaceReserve: volume