apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: backend-tbc-argocd-default
spec:
  version: 1
  backendName: argocd-nas
  storageDriverName: ontap-nas
  managementLIF: 192.168.0.135
  storagePrefix: argocd1_
  defaults:
    snapshotPolicy: default
  credentials:
    name: ontap-nfs-svm-secret-username