apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: argocd-storage-class-nas
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: csi.trident.netapp.io
parameters: