---
- hosts: localhost
  collections:
    - netapp.ontap

  vars:
    recurrent_parameters: &recurrent_parameters
      hostname: 192.168.0.210
      username: trident 
      password: Netapp1!
      https: true
      validate_certs: false
  
  name: Set Export Policy on Tenant Root
  tasks:
  - name: Gather Tenant Export Policy Information
    na_ontap_info:
      state: info
      gather_subset: "export_policy_info"
      <<: *recurrent_parameters
    register: netapp 

  - name: Modify root Export Policy
    na_ontap_volume:
      state: present
      name: root
      policy: "{{ netapp.ontap_info.export_policy_info[item].policy_name }}"
      vserver: svm_secured
      <<: *recurrent_parameters      
    with_items: "{{ netapp.ontap_info.export_policy_info }}"
    when: 
      - netapp.ontap_info.export_policy_info[item].policy_name is search('trident')